# Generated by Django 3.0.4 on 2020-03-18 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='highlighted',
        ),
        migrations.RemoveField(
            model_name='like',
            name='highlighted',
        ),
        migrations.RemoveField(
            model_name='profil',
            name='highlighted',
        ),
        migrations.RemoveField(
            model_name='profil',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='strangething',
            name='highlighted',
        ),
    ]
