# Generated by Django 3.0.4 on 2020-03-18 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200318_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='text',
            field=models.TextField(default='lala'),
            preserve_default=False,
        ),
    ]
