# Generated by Django 3.0.4 on 2020-03-18 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20200318_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='strangething',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like', to='api.Strangething'),
        ),
    ]
