# Generated by Django 3.0.4 on 2020-03-18 13:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0009_auto_20200318_1112'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('user', 'strangething')},
        ),
        migrations.AlterIndexTogether(
            name='like',
            index_together={('user', 'strangething')},
        ),
    ]
