# Generated by Django 3.0.4 on 2020-03-18 14:49

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0010_auto_20200318_1350'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together={('user', 'strangething', 'text')},
        ),
        migrations.AlterIndexTogether(
            name='comment',
            index_together={('user', 'strangething', 'text')},
        ),
    ]
